from typing import Protocol, List, Optional
from .article_entity import Article

class ArticleRepository(Protocol):
    def top(self, limit: int = 20) -> List[Article]: ...
    def search(self, query: str, limit: int = 20) -> List[Article]: ...
    def get(self, article_id: str) -> Optional[Article]: ...
